### ISSUE TITLE
Epoptes Not Launching On Pi

### ISSUE THREAD

**Issue by TheFlyingCrocodile** [PiNet/PiNet#112]
i cant get the epoptes to run on the pi when signed in as a teacher through the pinet menu i even modified manually /etc/group
i am running the beta 1.2.8 i can manually run it with ltsp-remoteapps

**Comment by gbaman** [comment]
@TheFlyingCrocodile when I get a free second over the next week or 2, I will try and take a look into this. Given the PiNet application is running over remote-apps, any applications spawned from it should also work.

Will take a look.

**Comment by gbaman** [comment]
Scratch that, just seeing the issue is closed. @TheFlyingCrocodile did you get it working?

**Comment by TheFlyingCrocodile** [comment]
@gbaman no not sure why I closed it to be honest, I guess it's because I got it to work manually with a .desktop file but still does not work via pinet menu

**Comment by TheFlyingCrocodile** [comment]
@gbaman no not sure why I closed it to be honest, I guess it's because I got to to work manually with a .desktop file but still does not work via pinet menu

**Comment by gbaman** [comment]
I can't seem to reproduce this one. If is still an issue, feel free to reopen.
