### ISSUE TITLE
Unable to install Jessie version

### ISSUE THREAD

**Issue by jbartucz** [PiNet/PiNet#115]
I created a fresh install of Ubuntu 16.04 on a machine and when I tried to install the Jessie alpha version, I got a bunch of errors. I have attached screen shots (sorry for the potato quality).

![2017-08-14 14 42 07](https://user-images.githubusercontent.com/20408120/29334976-cfc80772-81ce-11e7-9bf6-a221371a5021.jpg)
![2017-08-14 14 41 44](https://user-images.githubusercontent.com/20408120/29334978-cfc8f6be-81ce-11e7-9a86-b702031a180d.jpg)
![2017-08-14 14 42 00](https://user-images.githubusercontent.com/20408120/29334977-cfc83364-81ce-11e7-914a-e0f7dcac37a8.jpg)

**Comment by gbaman** [comment]
I am going to take a look at this one now, it is likely an issue with packages released by the Raspberry Pi Foundation and the way PiNet holds some of those packages back until they are tested by me.
Will report back

**Comment by jbartucz** [comment]
It's not critical as I will use the Wheezy version in my classroom. Just thought you should know. Thanks!

**Comment by gbaman** [comment]
Well, I would be recommending you use the Jessie version if at all possible as it is better supported by myself and the Raspberry Pi Foundation.
The Wheezy release, although generally very stable, hasn't had many updates bar security for 2 years now.

**Comment by jbartucz** [comment]
Ok, I'm definitely willing to do that if I can get it to boot. The installation page is full of warnings about using it, though. Definitely willing to help you test it in any way that would be helpful. I'm not going to need my lab up and running for several weeks.

**Comment by gbaman** [comment]
I probably should really remove those :)
It has been in testing since December 2016 through different stages and is near enough should be sitting in the stable channel by now, just Stretch is coming along now soon so it is getting my attention. It will be a nice in place upgrade though.

**Comment by jbartucz** [comment]
Ok, so I think I made some progress in finding the error: I tried reinstalling everything and got the same error screens as above. When I try to run the commands in a separate terminal, I get the following error:

```
The following packages have unmet dependencies:
raspberrypi-sys-mods : Depends: systemd (>= 230) but 215-17+deb8u7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by gbaman** [comment]
Can I check, are you installing PiNet on a filtered internet connection (for example in a school) or an unfiltered internet connection?

**Comment by jbartucz** [comment]
Unfiltered (in my basement). Although I do have a pihole running.

**Comment by gbaman** [comment]
I finally got to the bottom of the issue, was an issue with the way PiNet handles some packages. I have done some fiddling around with the PiNet apt server which should resolve it for now till I can get more time to put in place a more permanent solution.
Give it another install and see if that works now @jbartucz

**Comment by jbartucz** [comment]
During the installation process, I have been selecting the "stable" release channel. Should I be selecting the "beta" or "alpha" instead?

**Comment by gbaman** [comment]
Ahhh, that probably explains why I couldn't reproduce it as easily, as you had mentioned alpha in the initial issue comment so I was running with the alpha code.
Is it working after the fix yesterday evening?

**Comment by jbartucz** [comment]
Makes sense - I was just following the instructions and wasn't smart enough to associate alpha version with alpha release channel. Sorry about that. 

Looks like it installed successfully. I only saw a couple minor issues. I'll close this issue.

If you want help updating the installation instructions, just send me a message.
