### ISSUE TITLE
multiple 'command "sudo ltsp-chroot....." failed to execute correctly with a return code of 100' errors.

### ISSUE THREAD

**Issue by badsketch** [PiNet/PiNet#119]
Hi there,
I keep running into 'Command failed to execute' errors for different packages like i2c tools, python digitalio like in the screenshot below. While I have pressed 'Continue', there have been over a dozen now so I'm afraid that there are more serious issues.

![screenshot from 2017-08-25 13-23-11](https://user-images.githubusercontent.com/8953212/29731313-cc5c413a-8998-11e7-8087-c4b841cc9abe.png)

I am currently running Ubuntu 16.04 using Wubi for dual boot.  I am trying to install PiNet Jessie Beta.
I have tried entering
```
sudo apt-get install ubuntu-restricted-extras
sudo apt-get update && sudo apt-get upgrade
```
prior to installing PiNet, but I still run into this.

If it helps, I took a screenshot between the purple error screens to see what the terminal was outputting.
![screenshot from 2017-08-25 13-10-54](https://user-images.githubusercontent.com/8953212/29731148-383f9f56-8998-11e7-9405-8dd2a91529b9.png)
![screenshot from 2017-08-25 12-21-52](https://user-images.githubusercontent.com/8953212/29731150-3ceef286-8998-11e7-8ea2-fdfb391863e1.png)

Any help/advice is appreciated!
Thanks in advance.

**Comment by gbaman** [comment]
To check, are you running your PiNet server behind any sort of web filtering? Or is this installation taking place behind a corporate/school filtered web connection?

**Comment by badsketch** [comment]
Yes, the installation is taking place behind a school filtered web connection.  It's a bit strange though, because I have successfully installed PiNet the same way on the same connection in the past without bumping in those messages and on my home network, which shouldn't be filtered, I have ran into these issues.

**Comment by gbaman** [comment]
The errors are suggesting it can't reach the archive.raspberrypi.org site, which is the main Raspberry Pi Foundation maintained repository for packages. Unfortunately that is out of the scope of PiNet itself at that stage. The fact it can't resolve archive.raspberrypi.org suggests either your DNS server is having some issues, their DNS server is having some issues, or something is blocking the traffic in the middle.
Can you try on a web browser from the PiNet server seeing if you can access it? I can confirm I can currently

**Comment by badsketch** [comment]
I think you were right about the web filtering possibly causing it.  I switched from the lab/office connection to the school wide network and I stopped running into these errors.
Thanks!

**Comment by KwesiAsamoah** [comment]
I was having the same problem, i solved it by adding Raspbian Repository to my sources list

-  `sudo nano /etc/apt/sources.list` 

- add this to the end of the file 
```
 deb http://archive.raspbian.org/raspbian wheezy main contrib non-free
 deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free
 ```
-   hit `ctrl + x` then `y` then `enter` to exit out of nano

If needed, you can store the Raspbian public key into your apt-get keyring using the following command: 
`wget https://archive.raspbian.org/raspbian.public.key -O - | sudo apt-key add -`

**Comment by gbaman** [comment]
@KwesiAsamoah PiNet does everything mentioned above?

Adding Raspbian repository - https://github.com/PiNet/PiNet/blob/jessie-stable/pinet#L344
Adding key - https://github.com/PiNet/PiNet/blob/jessie-stable/pinet#L201

Do note, that as is generally best practice, the apt repo is added by PiNet to a separate file in /etc/apt/sources.d, as opposed to directly in the main sources.list file.


So there will be another underlying issue with your web connection (or may have been when you first tried), as was the case for the other user in this issue.

If you instead mean you added it to the main Ubuntu OS, this is a **very bad idea**. The packages are not built for Ubuntu and may cause issues down the line.

**Comment by ghost** [comment]
Thank you for pointing that out to me.
