### ISSUE TITLE
No Server IP Address in Pinet

### ISSUE THREAD

**Issue by tyrower** [PiNet/PiNet#12]
Despite having Network Connectivity and being able to see my IP address via hostname -I, no address is showing up in the "pinet System Status" page. No IP address is thus shown in the PiBoot/cmdline.txt file after "nbdroot=". Running the troubleshooter has not resolved the anomaly.

Even by manually entering the IP of my server machine running pinet, the Raspberry Pi will not boot (cannot see the server).

Any ideas or suggestions? How would one go about doing a "fresh install" or "uninstall/reinstall" of Pinet?

Ubuntu Desktop 14.04LTS (32bit)
Pinet version 1.0.4

**Comment by gbaman** [comment]
To check, have you manually entered the server IP address in `nbdroot=` on the SD card?
Sometimes if there is multiple network cards (or eth0 isn't being used), PiNet can get a little confused.
It pulls the IP address via ifconfig.
As for a fresh install, that is completely reinstalling Ubuntu from scratch, then PiNet.
