### ISSUE TITLE
PiNet with chromebooks 

### ISSUE THREAD

**Issue by badsketch** [PiNet/PiNet#125]
Sorry if this question isn't suitable under issues.

I'm wondering what type of implementations are available for connecting the peripherals of a network of Raspberry Pi's?  For example, I can hook up monitors and keyboard/mice to each of them.  Also, I saw an image of a classroom using Motorola lapdocks.  Now I'm wondering if I can instead use VNC Viewer on Chromebooks if a classroom is only equipped with those.  I've tried, but VNC Viewer can't connect.  Is it because each RaspberryPi is connected via an ethernet cable in a closed LAN?

Any help is appreciated.

**Comment by gbaman** [comment]
@danielwang405 unfortunately not, PiNet is only designed for having monitors plugged directly into the Pis, as opposed to VNCing into the Pis.
This is all to do with the login side of things, which is only presented to the plugged in monitor as opposed to via VNC. So you can't easily log into a user account then as the user accounts don't actually exist on the Pis. Although LTSP (and so PiNet) does support auto logging in, then you are stuck with all the Pis logging in with the same credentials.

The picture with the lapdocks was simply the Pis each plugged into the lapdocks microHDMI input on the back, having them act as normal screens/keyboards/trackpads.
