### ISSUE TITLE
Jessie Install Issue

### ISSUE THREAD

**Issue by jbartucz** [PiNet/PiNet#134]
Hello,

  Just put Ubuntu Desktop 16.04 LTS on a fresh machine, did update and upgrade. Downloaded jessie-stable-pinet, tried to install and am getting sudo error code 127. If I "continue", it just keeps happening. Image: https://www.dropbox.com/s/ug4a9x0p382358g/2017-11-11%2011.06.14.jpg?dl=0.

Thanks,
John

**Comment by jbartucz** [comment]
Ran it again and it worked. Closing.

**Comment by gbaman** [comment]
Yeah, I think this may have been related to issues with the Raspbian repositories having issues over the weekend. We had issues at the NI Raspberry Jam installing stuff as well.
