### ISSUE TITLE
sudo ltfs-chroot commands giving error code 126.

### ISSUE THREAD

**Issue by KlwntSingh** [PiNet/PiNet#136]
Hi There,
I am trying to install PINet on Ubuntu xenial distro and couple of **ltfs-chroot** commands are failing giving return code 126. 
Below is pinet.log file
> 2017-12-08 13:56:13,942 root         DEBUG    Downloaded file from https://raw.github.com/pinet/pinet/jessie-stable/Scripts/kernelCheckUpdate.sh to /tmp kernelCheckUpdate.sh.
> 2017-12-08 13:56:14,237 root         INFO     Adding new group to the Raspbian chroot - gpio
> 2017-12-08 13:56:14,252 root         WARNING  Command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'gpio', '-g', '625']" failed to execute correctly with a return code of 126.
> 2017-12-08 14:00:17,377 root         INFO     Failed command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'gpio', '-g', '625']" was ignored and program continued.
> 2017-12-08 14:00:17,379 root         INFO     Adding new group to the Raspbian chroot - spi
> 2017-12-08 14:00:17,409 root         WARNING  Command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'spi', '-g', '626']" failed to execute correctly with a return code of 126.
> 2017-12-08 14:00:18,100 root         INFO     Failed command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'spi', '-g', '626']" was ignored and program continued.
> 2017-12-08 14:00:18,102 root         INFO     Adding new group to the Raspbian chroot - pupil
> 2017-12-08 14:00:18,132 root         WARNING  Command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'pupil', '-g', '628']" failed to execute correctly with a return code of 126.
> 2017-12-08 14:00:18,500 root         INFO     Failed command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'pupil', '-g', '628']" was ignored and program continued.
> 2017-12-08 14:00:18,501 root         INFO     Adding new group to the Raspbian chroot - teacher
> 2017-12-08 14:00:18,532 root         WARNING  Command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'teacher', '-g', '629']" failed to execute correctly with a return code of 126.
> 2017-12-08 14:00:18,910 root         INFO     Failed command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'teacher', '-g', '629']" was ignored and program continued.
> 2017-12-08 14:00:18,911 root         INFO     Adding new group to the Raspbian chroot - i2c
> 2017-12-08 14:00:18,942 root         WARNING  Command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'i2c', '-g', '627']" failed to execute correctly with a return code of 126.
> 2017-12-08 14:00:19,355 root         INFO     Failed command "['sudo', 'ltsp-chroot', '--arch', 'armhf', 'groupadd', 'i2c', '-g', '627']" was ignored and program continued.
> 2017-12-08 14:00:22,108 root         DEBUG    Deleting theme cache for ubuntu.
> 

I have attached the screenshots of errors and of Ubuntu distro details.

![2017-12-07_first](https://user-images.githubusercontent.com/10296556/33768733-a03be9e0-dbfd-11e7-9c54-ace045aec7aa.png)

![2017-12-07_second](https://user-images.githubusercontent.com/10296556/33768739-a5872bf8-dbfd-11e7-8d31-36fa9410768d.png)

![2017-12-07_fourth](https://user-images.githubusercontent.com/10296556/33768745-aa7e67f2-dbfd-11e7-9b7d-43e5b16889b1.png)

![2017-12-07_fifth](https://user-images.githubusercontent.com/10296556/33768747-ac2a19ca-dbfd-11e7-9b3f-e8ef366a95e7.png)

![2017-12-07_lsb_release](https://user-images.githubusercontent.com/10296556/33768754-b2772552-dbfd-11e7-8cd9-b6acb0168471.png)

Thanks in Advance!

**Comment by KlwntSingh** [comment]
Please Help related to above issue.

**Comment by gbaman** [comment]
Apologies, I missed this one coming in. Can I check the first one, is this PiNet server being installed being a school firewall or otherwise limited (or unreliable) internet connection?

Also, is the Ubuntu installation a fresh clean install with no additional software and a single user account (besides root)?

**Comment by KlwntSingh** [comment]
Hi There,
Thanks for replying.
I am installing PiNet server in my home environment and also internet connection is reliable.
Yes, Ubuntu is fresh clean install, Actually i am installing PiNet server inside of lxc-container of ubuntu xenial version.

Thanks

**Comment by gbaman** [comment]
Unfortunately I am unable to provide support for PiNet running inside a containerised environment given so many other things are then at play.
The only suggestion I would have to help better understand what is going on is if you can get a screenshot of the full error message of one of the commands.
For example
``` sudo ltsp-chroot --arch armhf groupadd i2c -g 627```

**Comment by KlwntSingh** [comment]
Hi,
Already Attached screenshots is the only error messages I am getting.
I will try to run PiNet outside container than, it could be the reason.

Thanks for help!

**Comment by gbaman** [comment]
@KlwntSingh the PiNet logs (which you attached) don't capture the full output/error message of the command, hence why I need you to if possible try running the suggested command directly in a terminal, to capture the full output.
The logs unfortunately only capture the command being run and the error code it failed with, which isn't useful in this case.

**Comment by KlwntSingh** [comment]
Hi @gbaman 
Definately I will check and and will respond you back with logs.

Thanks

**Comment by gbaman** [comment]
@KlwntSingh Given no response in a month now, am closing this issue. Please re-open if is still an issue.
