### ISSUE TITLE
PDF Viewer Suggestions

### ISSUE THREAD

**Issue by fearnma** [PiNet/PiNet#145]
Hi Andrew,

Sorry to disturb you again but can you recommend a good pdf viewer I can install through pinet to the pis?  Whats the software id?  e.g. scratch2 will install scratch.

Matt

**Comment by gbaman** [comment]
Well, there are many PDF viewers. PiNet includes xpdf (which is rather old), but new Raspbian images are going to default to qpdfview apparently, so you could give it a go.
The package name is simply - qpdfview
https://github.com/RPi-Distro/pi-gen/commit/1f51b8bd18bc21f4d9af05e9a32348001597dae8
