### ISSUE TITLE
Spyder and Python version

### ISSUE THREAD

**Issue by harrywt** [PiNet/PiNet#148]
I installed Spyder using PiNet on my Ubuntu server. I explicitly typed "Syder3". Spyder starts up fine on the RPi's but it seems to be using Python 2 instead of Python 3.

I can find no documentation explaining how to have Spyder install using Python 3. 

I can find no documentation explaining how to UNinstall a package in PiNet, only how to install.

Maybe I don't even have a problem, it just seems prudent to go with Python 3. Also, maybe PiNet would "allow" Spyder with Python 3

Any insights would be appreciated

**Comment by gbaman** [comment]
So @harrywt I have no experience with Spyder, but can I confirm if similar takes place on a standard Raspbian standalone install, or is it just on PiNet?
