### ISSUE TITLE
Desktop link issues

### ISSUE THREAD

**Issue by gldneagl** [PiNet/PiNet#150]
I have tried several time to install Pinet on virgin builds of both Ubuntu 16 and Ubuntu-Mate 16 desktop versions so I tried the Ubuntu 16 server version and ended up with this same issue... desktop links that do not work after what seems otherwise to be a successful full install.

![screenshot at 2018-07-17 13_42_14](https://user-images.githubusercontent.com/6347330/42838870-85450c0c-89c7-11e8-8bf1-534a7173e88d.png)
.

**Comment by gbaman** [comment]
@gldneagl the desktop links should not work on the PiNet server. They are actually desktop links for use on the Raspberry Pis. They just carry over to the server as well as the same account can be used in both places.

**Comment by gldneagl** [comment]
@gbaman Thank you...
but wouldn't it be "tidier" if they weren't right on the desktop on the server?
If I hide them on the desktop, will it affect them on the Raspbery Pis?
Seems nothing is actually broken, so please feel free to close this.

**Comment by gbaman** [comment]
@gldneagl It certainly would be tidier yes, but I am not aware of a way to hide them without it also hiding on the Pi. The Desktop folder is part of the users home folder, so is the same no matter where you log in unfortunately.
I certainly do rather wish there was a nice and clean way to do it...

**Comment by gldneagl** [comment]
I am going to investigate, since having them in the folder I created for them on the server desktop meant that the update SD card scripts couldn't find them. I moved them back out of the folder, and voila!, the update went without an error about not finding pinet-password.desktop
