### ISSUE TITLE
PiNet login screen username string is cut off

### ISSUE THREAD

**Issue by lobustho** [PiNet/PiNet#152]
Hi folks,

in the German localisation string for user "Benutzername" is to long and therefore cut off. 
Is there a way to customize the layout/font size of the login screen and/or the string itself?

Thanks in advance

**Comment by gbaman** [comment]
So that bit is actually part of LDM, which is part of LTSP itself which PiNet sits on top of. As such, I will admit I am not 100% sure best course of action. 
@alkisg you don't happen to have any suggestions? (or with this one? https://github.com/PiNet/PiNet/issues/153)
