### ISSUE TITLE
How to change client hostname

### ISSUE THREAD

**Issue by squadramunter** [PiNet/PiNet#156]
Greetings,

I wonder how can I change the hostname from the clients?

The default hostname is ltsp60 now.

I hope someone can help me with this.

**Comment by gbaman** [comment]
PiNet itself doesn't have this brought out to any GUI, but you can make tweaks like that directly to the underlying LTSP configuration.
Edit the lts.conf file at `/opt/ltsp/armhf/etc/lts.conf`
The available values are here - https://manpages.ubuntu.com/manpages/bionic/man5/lts.conf.5.html
The key one you probably want to add is `HOSTNAME_BASE=whatever`

Then make sure to recompress the OS from the Other menu in PiNet and reboot the Pis.
