### ISSUE TITLE
Reboot / Shutdown not working on RPI 3B+?

### ISSUE THREAD

**Issue by squadramunter** [PiNet/PiNet#157]
When I try to Shutdown or Reboot the raspberry it looks like it is stuck at the point it says rebooting.

This does not happen always.

Anyone facing same problem?

I use the latest version 1.3.3

**Comment by gbaman** [comment]
This is a known issue with PiNet Stretch, although has been a low priority. I have though added it to the big list. https://github.com/PiNet/PiNet/issues/142

Keep them coming 👍 

As this is now on the main list, I will go ahead and close this individual issue.
