### ISSUE TITLE
No validation on shared folder names

### ISSUE THREAD

**Issue by vinnievg** [PiNet/PiNet#3]
Just testing... I tried to create a shared folder with spaces in it (not the best idea in Linux - although not impossible)  pinet creates a folder based on first word, but then failed to apply the permission correctly.

I recommend the imput string be checked for spaces and any special characters apart from _ and -

PiNET is looking very good - performance is very good.

**Comment by gbaman** [comment]
Great find, thanks. Will see about getting a fix for it.
