### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by tjguk** [PiNet/PiNet#30]
Within reason it would be good to conform to PEP8 guidelines for code readability. I don't believe we have to be slavish, to the extent of having github hooks reject non-compliant code. But at present there's a mixture of Bash & Java conventions.

I would probably avoid doing this wholesale; rather, I'd reformat code as we're in the process of reworking it anyway for some reason

**Comment by gbaman** [comment]
Have finally been getting somewhere on this. The new WorkingOnJessie branch includes the newly reformatted Python code to more closely follow PEP8. Only 209 errors left and most are simply line too long errors - https://github.com/PiNet/PiNet/tree/WorkingOnJessie
