### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by fearnma** [PiNet/PiNet#42]
Dear Pi Net,

I have now set up my laptop with Ubuntu and also downloaded and installed pi-net.  I have been having boot up issues with the pi where it only gets to initramfs prompt.  I am though able to ping the laptop from the pi and connection is made. and also ping the pi from the laptop. 

As I can ping the laptop I am wondering if there are some config steps with the router which I maybe need to alter in order for a direct link to be formed.

DHCP setting

Under IPv4 Settings

On the connect do I need to set this as?

Automatic

Automatic DHCP addresses only

Manual

Link-Local Only

Shared to other computers

disable (guessing not this)

IPv6 Settings

Can this be automatic or need changing?

What i am noticing is I can not get a secure connection to the router through the ethenet and the wireless connection kicks in first.

The router I am using is

http://www.asus.com/uk/Networking/RTN56U_B1/

Thanks in anticipation for the support

Is there anyone in the Manchester area using your set up for whom I could visit to explore what I am doing wrong?

Thanks
Twitter fearnm

Matt

**Comment by gbaman** [comment]
Being sorted over email.
