### ISSUE TITLE
Shutdown & Reboot not working

### ISSUE THREAD

**Issue by marc-odp** [PiNet/PiNet#43]
To quit session on the client, there are 3 options in the dialog box : Shutdown - Reboot - Logout
Shutdown & Reboot don't do anything. Logout works.
So, to shutdown, the only option is to Logout and on the login screen to choose 'Preferences' on the bottom left. In that menu 'Shutdown' works.
Ubuntu 15.10 + Pinet 1.1.4

**Comment by kusti8** [comment]
It looks like it's because sudo access is restricted?

**Comment by marc-odp** [comment]
Thank you for your response. During install, I responded 'no' to the option 'enable the use of sudo for pupils. Used for GPIO access' because we don't plan to use GPIO. So you think this is a side effect of not activating that option ?
I don't have the possibility to try to change this at the moment (no access to computer). I will try when I have a possibility...

**Comment by kusti8** [comment]
Yes, that's been my experience. I don't develop for Pinet, but that looks
how it works. But your students shouldn't need to shut it down. You should
actually be able to pull the power since it's all on the server.

**Comment by marc-odp** [comment]
Your are right, this is certainly not a 'major' problem. However, it seems funny to teach students the proper (and safe) way to shutdown a computer on one side and on the other side to tell them to just remove the plug in this particular Pinet network configuration...

**Comment by kusti8** [comment]
I agree. For now, just logout and then shutdown from there.

**Comment by gbaman** [comment]
I am going to see about properly fixing this in PiNet Jessie, it should just mean giving users of the `pupil` group access to shutdown, reboot and halt.

**Comment by gbaman** [comment]
This bug has now been fixed in the new Jessie development branch.
https://github.com/PiNet/PiNet/commit/c19445e91ff362e6fac9331476fb2223db0ca79a
