### ISSUE TITLE
Pinet start error (/warning) Xsession

### ISSUE THREAD

**Issue by marc-odp** [PiNet/PiNet#44]
I have a strange non-blocking error after the login in the Rapberry Pi client (please see image). It shows the
message "unable to launch "gnome-session --session=ubuntu" X session
--- "gnome-session --session=ubuntu" not found; falling back to default session."
Ubuntu 15.10 + Pinet 1.1.4
![_pinet_error_imag4781](https://cloud.githubusercontent.com/assets/17361839/13198530/0ea8a800-d831-11e5-8637-61e5fda8680e.jpg)

**Comment by gbaman** [comment]
This is no issue. Is simply a warning and it should fire up LXDE after hitting okay. It only happens to accounts that have been logged into on the Ubuntu server, as Ubuntu overwrites the preferred desktop environment. Given it can't find that, it will simply fall back to LXDE.
