### ISSUE TITLE
Ubuntu PiNet Server

### ISSUE THREAD

**Issue by ddezellem** [PiNet/PiNet#47]
I am attempting to create a local network of pi computers using an old laptop with Ubuntu and a bunch of raspberry pi's.  Right now I have four set up with the Pinet software downloaded and the SD cards formatted.  Unfortunately when I check my system status for PiNet my Server IP address is blank.  I believe this is why I am getting the '/bin/sh: can't access tty; job control turned off' error message. 

Any ideas before I try full reboot?

**Comment by gbaman** [comment]
What is the setup of your network? Is there a DHCP server on the network to hand out IP address (router usually)? Does the server itself have internet access?

Also, are you using a virtual installation (using virtualbox), or just installed directly onto the server computer hardware?

It may be possible the PiNet software simply wasn't able to detect the IP address of your server due to a wacky network setup. If that is the case, you can just manually edit the cmdline.txt file on the SD card to the address the server does have.
http://pinet.org.uk/articles/troubleshooting/boot-issues.html

**Comment by ddezellem** [comment]
Here is my current hardware:

I have my Ubuntu computer installed with PiNet hooked up to a router which is hooked up to a giga port switch which goes out to 4 raspberry pi's with the necessary software for PiNet.  

I am not sure what installation I am using...

I did manually update each of the SD cards in the cmdline.txt file to 192.168.0.125
this was what each of them had which I believe came with the installation.  

I was on my home network when I downloaded Ubuntu, PiNet, and installed the SD cards.  Now I am at school where I do not have access to the network with any of this hardware. Would my IP address have changed can I manually set the router?

Thanks

**Comment by gbaman** [comment]
To explain by the way, (/bin/sh:can’t access tty…..) isn’t actually an error, it appears on all bootups with PiNet. It just happens to be getting stuck on the next bit, which in this case is it connecting to the PiNet server.

Yes, your IP address of the server will change when it is brought into school. You will need to update the cards with the address your server has been allocated by the router. It is also recommended if you can edit the configuration of the router, to give the PiNet server a DHCP reservation (basically the router reserves an IP address for it)

Could you go up to the top right of the Ubuntu desktop and click on the 2 arrows (pointing opposite directions), followed by connection information. Is an IP address being shown in the IPv4 section?
If there isn't an address there, then your router is not handing out IP addresses to devices attached to it.

**Comment by ddezellem** [comment]
I have the wireless signal which is the four curved lines but I have wireless disabled. The connection information is under that icon but it is not lit up, I cannot click on it.

**Comment by gbaman** [comment]
Then that means the server is not connected to the network. Can you double check the LEDs on the network port on the server is actually flashing? Perhaps try a different Ethernet cable or port on the router?

**Comment by ddezellem** [comment]
Alright the router is connected now I have the arrows and the connection information lists an IPv4.  It has an IP address, a broadcast address, etc.

**Comment by ddezellem** [comment]
When I ping the server from the raspberry Pi I get 3 packets transmitted, 0 packets received, 100% packet loss.
That tutorial you showed me did not solve that particular issue.

**Comment by gbaman** [comment]
Are the network lights flashing on the Raspberry Pi as well? Can you upload a screenshot of what happens when you run `ifconfig` on the initramfs shell on the Raspberry Pi after it fails to boot?

**Comment by ddezellem** [comment]
Noting is flashing, the only reason I thought it was fixed was because the connection information became available.  Everything is hard wired through cat 5
cables, I even turned the wireless off on the router.  My Ethernet cables go as follows from computer to internet port on router, from port one on router to
giga port switch port 1, from ports 2, 3, 4, 5 to raspberry pi's...
Picture of screen after ifconfig is attached

**Comment by gbaman** [comment]
No picture unfortunately came through (might be better to reply directly on Github so you can attach it?).  
If the lights on the Raspberry Pi aren't flashing, then that means there is no traffic going across the wire. This means most likely either a dodgy cable or dodgy network switch. Would it be possible to try it with a different network cable/switch?  
No lights flashing on the Pi end though makes it very unlikely it is a Pi issue. Can I double check what Raspberry Pi model you are using?
