### ISSUE TITLE
Spell checker in Libre Office does not work (no en-gb dictionary)

### ISSUE THREAD

**Issue by mr-eggleton** [PiNet/PiNet#52]
I have fixed locally by ...

``` bash
sudo ltsp-chroot --arch armhf

apt-get install myspell-en-gb  mythes-en-us
apt-get remove hunspell-en-us

exit
ltsp-update-image /opt/ltsp/armhf

```

**Comment by gbaman** [comment]
Thanks for reporting and including a solution. I have added it to most recent [development snapshot](https://github.com/PiNet/PiNet/commit/d20d98c41f2ed6b69933ecdc8f8ef62cac2d8017#diff-e9dbff4c7456910bfddfab7041ec798cR1503), hopefully to be properly released soon.
Will leave the issue open till is properly released and tested.

**Comment by mr-eggleton** [comment]
This seems to be in a Jessie related branch. Is Jessie now used if you pick the standard   “Dev (development”) option rather than “Master (stable)”? or do we still need to use the instructions here http://pinet.org.uk/articles/advanced/custom-branches-repositories.html  I have a class that really needs Jessie in September.

**Comment by gbaman** [comment]
Jessie development is still being kept separate from the Wheezy branches for now. Haven't had much time to work on it over past few months and think most would prefer stability over new features, especially in schools. So stable and development channels in the PiNet software still point to Wheezy releases.
The WorkingOnJessie branch is simply that, for me to upload code am working on and test. It isn't for general use and the instructions in the custom-branches documentation won't work for it, given each upload doesn't have a separate release version. They will eventually be squashed (using new Github feature) into a single release when Jessie is looking more usable.
