### ISSUE TITLE
Background update checking

### ISSUE THREAD

**Issue by gbaman** [PiNet/PiNet#57]
Right now, PiNet checks for updates each time the main control panel is opened. Although simple, this has a few drawbacks
1. It adds time to the startup of the control panel, usually a few seconds.
2. If opening the control panel a number of times in a row, means it will check each time (increasing time wasted)
3. If the panel isn't opened for an extended period of time, users will be unaware of available updates which could fix bugs/issues with the software in use.

Was thinking, a better way to do it might be simply have a cron job running every few days checking for updates and writing result to a file. When PiNet software is started, if checks this file and compares current version to version in the file. If they are different when PiNet control panel is started, it rechecks again and informs the user.
If when the PiNet control panel starts, the timestamp on the file is older than x days, then can assume was an issue last time the cron job was run so manually checks, like we have right now.

To solve the 3rd point, perhaps if the user logging into a Pi is in the teacher group, they can be notified of a new update when they log in (which they can then mute if required)?

Opinions?

**Comment by TheFlyingCrocodile** [comment]
@gbaman i like the idea of teachers logging in and being notified as i run the pinet server from a vm and rarely open the vnc for it. in terms of updates is there no easy way to "push" updates to the servers instead of checking every now again, but id imaging that would add security concerns.
