### ISSUE TITLE
Investigate SSH issues

### ISSUE THREAD

**Issue by gbaman** [PiNet/PiNet#59]
Right now, if you try and SSH into one of the booted Pis, it won't work, will simply be refused a connection.
Although not a key requirement for PiNet, it is needed by people wanting to use PiNet for stuff like clusters etc.
It used to work fine in Wheezy, but with Jessie it is no longer working.

After some investigating, looks like the Pis don't actually have SSH keys... My guess is it is to do with the way LTSP cleans up the clients when being prepped, assuming the clients would regenerate their keys on boot which doesn't seem to be happening.

A temp fix is to run `ssh-keygen -A` on each boot, but that isn't a great answer. Will need some more investigating.

**Comment by youngole** [comment]
Is it possible as a temporary fix to add this line to rc local to run the command at every boot?

**Comment by gbaman** [comment]
Although doable, isn't a viable long term solution. Becomes more of an issue to then remove a quickfix like this later down the line.
I have no doubt that it would probably work and can be implemented manually if users need SSH access (only a very small minority do)
