### ISSUE TITLE
InstallPipPackage vs pip install -r requirements.txt?

### ISSUE THREAD

**Issue by Lewiscowles1986** [PiNet/PiNet#65]
Not sure if there is a reason behind this I don't know (apologies in advance if there is)

you've made a function InstallPipPackage, which could be replaced by 

``` bash
cat > ./pi_pip_requirements.txt  <<EOF
gpiozero>=0.0.1
pgzero>=0.0.1
pibrella>=0.0.1
skywriter>=0.0.1
unicornhat>=0.0.1
piglow>=0.0.1
pianohat>=0.0.1
explorerhat>=0.0.1
twython>=0.0.1
EOF

pip install -r pi_pip_requirements.txt
```

https://pip.readthedocs.io/en/1.1/requirements.html

**Comment by gbaman** [comment]
The reason for installing each PyPi package individually is in case any individual package fails to install, the others aren't also blocked from installation. Although a hybrid approach (try all, if fail do each individually) is possible, given there are only a small set of PyPi packages to be installed, it isn't really worth it.
