### ISSUE TITLE
sed /d duplicates

### ISSUE THREAD

**Issue by Lewiscowles1986** [PiNet/PiNet#67]
https://github.com/CODESIGN2/PiNet/blob/master/pinet#L1049

```
sed --in-place '/PiNet.backup/d' /etc/anacrontab
sed --in-place '/PiNet.backup/d' /etc/anacrontab
sed --in-place '/PiNet.backup/d' /etc/anacrontab
```

could remove the two duplicate following lines to read 

`sed -i '/PiNet.backup/d' /etc/anacrontab`

running the delete line will by default remove the line and continue.

**Comment by gbaman** [comment]
As inefficient as it may look, for 3 lines a loop wasn't really worth it. The reason for it is multiple backups can be scheduled so needing replaced. This is why it is in there 3 times, just in case.
