### ISSUE TITLE
Import users by CSV fails to select file

### ISSUE THREAD

**Issue by agazendam** [PiNet/PiNet#69]
Bug identified and fix proposed.

When using the Manage-Users -> Import-Users menu function, only the initial directory displayed by whiplash allows for the selection of a file. When navigating further no more files are displayed. The bug was found in the SingleFileSelect bash function of the pinet file, line 1085 to be specific. This line should contain SingleFileSelect (capable of selecting files), instead of fileSelect (capable of selecting directories). Changing this line fixes the bug.

**Comment by gbaman** [comment]
Thanks @agazendam for tracking this one down. I have committed a fix in the new PiNet Jessie codebase, which should hopefully be going live soon.
https://github.com/PiNet/PiNet/commit/3c7a899606c2b9dd7bcec6fd088245d2c0f64ca3
