### ISSUE TITLE
pinet users on second drive

### ISSUE THREAD

**Issue by kc8cpw** [PiNet/PiNet#91]
I'm not sure where I need to go to ask questions, so I will ask here.

I have pinet server running on a 60GB SSD. I also have a second drive a 320GB HD (to be updated later since I'm just testing Jesse at the moment)

When I create users it places their home folder and stores all their data on the 60GB SSD Boot Drive. 

My question is this:
Is it possible to change some line of code somewhere that will force these remote users home folders to be created on the 320GB HD, or possibly give us the option to choose which drive we want the user on if more than one drive is present?

Jonathan

**Comment by gbaman** [comment]
Given how specific a use case this is and the complexity of automating its implementation (without sometime going wrong and basically bricking the server), this is unfortunately unlikely to be added to PiNet as an option in the GUI.
PiNet though just uses Linux home folders and user accounts. You best bet is either a symlink, or the better answer is setting it us with fstab. [Ubuntu docs have what looks to be a pretty decent guide](https://help.ubuntu.com/community/Partitioning/Home/Moving) that might be worth giving a go?
